/**
 * Vedika JavaScript/Node.js SDK
 * The only B2B astrology API with AI-powered chatbot queries.
 *
 * @packageDocumentation
 */

export { VedikaClient } from './client';

export type {
  VastuDrawingSheetRequest, VastuDrawingSheetData, VastuDrawingSheetResponse,
  VastuWorkspaceRequest, VastuWorkspaceData, VastuWorkspaceResponse, VastuWorkspaceOperation,
  VastuPlanImportImageRequest,
  VastuPlanImportPdfRequest,
  VastuPlanImportImageResponse,
  VastuPlanImportPdfResponse,
  VastuPlanImportData,
  BirthDetails,
  QuestionResponse,
  Citation,
  Planet,
  House,
  BirthChart,
  Dasha,
  DashaResponse,
  CompatibilityResponse,
  Yoga,
  YogaResponse,
  DoshaInfo,
  DoshaResponse,
  TimeWindow,
  MuhurthaResponse,
  NumerologyResponse,
  VedikaClientOptions,
  QuestionQuery,
  BirthChartQuery,
  CompatibilityQuery,
  MuhurthaQuery,
  NumerologyQuery,
  BatchQueryItem,
  V2Query,
  PredictionQuery,
  HoroscopeQuery,
  EnhancedQuestionQuery,
  VastuReportQuestion,
  VastuReportContext,
  ChartType,
  DashaSystem,
  DoshaType,
  MatchingType,
  MuhurtaType,
  DivisionalChartType,
  PredictionPeriod,
  StrengthType,
  NumerologyType,
  WesternRelationshipType,
  // TS→Rust transition-tolerant surfaces (3.0.6)
  SynastryAspect,
  WesternRelationshipResult,
  ResponseFormat,
  StructuredResponse,
  StructuredResponseSection,
  VoiceQuery,
  VoiceResponse,
  VoiceMetaHeader,
  VoiceResult,
  // Additional calculation types
  TarotCard,
  TarotReading,
  SpreadInfo,
  SpreadList,
  ChineseZodiac,
  BaZiChart,
  KuaResult,
  Hexagram,
  Crystal,
  BodyGraph,
  HDType,
  MatchResult,
  DoshaResult,
  MantraResult,
  DeityResult,
  PastLifeResult,
  DailyBundle,
  AllDashaResult,
  HealthResult,
  CareerResult,
  // Vastu (80 operations, 17 families)
  VastuMandalaScheme,
  VastuRoomType,
  VastuPlacementFeature,
  VastuAuditKind,
  VastuScoreKind,
  VastuArScanQualityInput,
  VastuArTrueNorthInput,
  VastuAssessmentsRequest,
  VastuAssessmentData,
  VastuAssessmentBadgeEligibility,
  VastuAssessmentsResponse,
  VastuJobIdOperation,
  VastuJobStatus,
  VastuJobsRequest,
  VastuJobResultItem,
  VastuJobSubmitData,
  VastuJobSubmitResult,
  VastuJobResultsPage,
  VastuJobStatusData,
  VastuJobResultsData,
  VastuJobsResponse,
  VastuJobsIdResponse,
  VastuJobsIdResultsResponse,
  VastuJobsIdCancelResponse,
  VastuJobResultsOptions,
  VastuChatUploadData,
  VastuChatUploadFile,
  VastuCallOptions,
} from './types';

// TS→Rust transition-tolerant value helper (3.0.6).
export { normalizeWesternRelationship } from './types';

export {
  VedikaAPIError,
  AuthenticationError,
  RateLimitError,
  DailyLimitExceededError,
  InsufficientCreditsError,
  SubscriptionExpiredError,
  ValidationError,
  TimeoutError,
  ServerError,
  NetworkError,
} from './exceptions';
export type { VedikaErrorDetails, RateLimitDetails, InsufficientCreditsDetails } from './exceptions';
export type { VedikaRequestOptions, VedikaHttpMethod } from './client';

// Package metadata
export const VERSION = '3.1.1';
export const AUTHOR = 'Vedika Intelligence';
export const HOMEPAGE = 'https://vedika.io';

export type {
  VastuCommerceBilling,
  VastuPropertiesCreateRequestIds,
  VastuPropertiesCreateRequest,
  VastuPropertiesUpdateRequestIds,
  VastuPropertiesUpdateRequest,
  VastuPropertiesGetRequest,
  VastuPropertiesListRequest,
  VastuPropertiesDeleteRequest,
  VastuPropertiesLinkScanRequest,
  VastuArchiveTierRequest,
  VastuArchiveExportRequest,
  VastuArchiveDeleteRequest,
  VastuArchiveSummaryRequest,
  VastuFeedListingsRequestRowsItemPlanAsset,
  VastuFeedListingsRequestRowsItem,
  VastuFeedListingsRequest,
  VastuQuoteCalculateRequestOperationsItem,
  VastuQuoteCalculateRequest,
  VastuPropertiesCreateData,
  VastuPropertiesUpdateData,
  VastuPropertiesGetData,
  VastuPropertiesListData,
  VastuPropertiesDeleteData,
  VastuPropertiesLinkScanData,
  VastuArchiveTierData,
  VastuArchiveExportData,
  VastuArchiveDeleteData,
  VastuArchiveSummaryData,
  VastuFeedListingsData,
  VastuQuoteCalculateData,
  VastuPropertiesCreateResponse,
  VastuPropertiesUpdateResponse,
  VastuPropertiesGetResponse,
  VastuPropertiesListResponse,
  VastuPropertiesDeleteResponse,
  VastuPropertiesLinkScanResponse,
  VastuArchiveTierResponse,
  VastuArchiveExportResponse,
  VastuArchiveDeleteResponse,
  VastuArchiveSummaryResponse,
  VastuFeedListingsResponse,
  VastuQuoteCalculateResponse,
} from './types';

export type {
  VastuWorkflowBilling,
  VastuRemediationTasksUpsertRequestTaskEvidenceItem,
  VastuRemediationTasksUpsertRequestTask,
  VastuRemediationTasksUpsertRequest,
  VastuRemediationTasksListRequest,
  VastuRemediationTasksDeleteRequest,
  VastuRemediationReassessRequestPlanRoomsItem,
  VastuRemediationReassessRequestPlanImportReview,
  VastuRemediationReassessRequestPlan,
  VastuRemediationReassessRequest,
  VastuMerchantCatalogUploadRequest,
  VastuMerchantCatalogGetRequest,
  VastuMerchantCatalogDeleteRequest,
  VastuMerchantRemediesRequest,
  VastuWorkflowData,
  VastuRemediationTaskData,
  VastuRemediationTasksUpsertResponse,
  VastuRemediationTasksListResponse,
  VastuRemediationTasksDeleteResponse,
  VastuRemediationReassessResponse,
  VastuMerchantCatalogUploadResponse,
  VastuMerchantCatalogGetResponse,
  VastuMerchantCatalogDeleteResponse,
  VastuMerchantRemediesResponse,
} from './types';
